# Generated by Django 4.1.1 on 2022-09-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mkoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jinalawilaya', models.CharField(max_length=50)),
                ('jinalamkoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.mkoa')),
            ],
        ),
    ]
