# Generated by Django 4.0.6 on 2022-09-29 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_udongomakundi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Udongotaarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taarifazake', models.TextField()),
                ('ainayaudongo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.udongomakundi')),
            ],
        ),
    ]
